#!/bin/bash

# Common module functions

# shellcheck disable=SC2174

mod_common_init(){
    local MOD_DIR="$RUNDIR/$MOD"
    mkdir -vpm 700 "$MOD_DIR"
}

mod_common_init_dev(){
    local MOD_DIR="$RUNDIR/$MOD"
    local STATUS_FILE="$MOD_DIR/$DEV_ID"
    echo "Monitoring for device $DEV_ID..."
    debug "Assuming device not connected, writing 0 to $STATUS_FILE"
    touch "$STATUS_FILE"
    chmod 600 "$STATUS_FILE"
    echo 0 > "$STATUS_FILE"
}

mod_common_info() # $1 (optional): a property to request, otherwise returns all
{
    case "$1" in
        desc) echo "$MOD_DESC" ;;
        type) echo "$MOD_TYPE" ;;
        backend) echo "$MOD_BACKEND" ;;
        deps)
            for DEP in "${MOD_DEPS[@]}"; do
                echo "$DEP"
            done
            ;;
        *)
            echo "Desctiption: $MOD_DESC"
            echo "Type: $MOD_TYPE"
            echo "Backend: $MOD_BACKEND"
            echo "Depends on: ${MOD_DEPS[*]}"
    esac
}
